### ISSUE TITLE
Allow no_camel_case by default

### ISSUE THREAD

**Issue by monospacesoftware** [antidot/Pyckson#15]
I don't see any way to set no_camel_case by default. Could you add something like `pyckson.configure_date_formatter`, but `pyckson.configure_no_camel_case()` so we don't need to add the decorator to every class?

Excellent lib in any case, thanks.

**Comment by JGiard** [comment]
I've added a `set_defaults` function to configure global behaviors. You can pass it any decorator that you would normally apply to a class, including the `date_formatter`.
`pyckson.set_defaults(pyckson.no_camel_case)`

https://pyckson.readthedocs.io/en/latest/advanced.html#defaults

it should be available in version 1.9.0
