### ISSUE TITLE
Enum values are not valorized

### ISSUE THREAD

**Issue by phptib** [antidot/Pyckson#19]
Hello,

Enums are generally used to hold a couple of information:

- an human readable name
- an optimized value used by computer

```python
class Status(Enum):
    ACCEPTED = "ACPT"
    DENIED = "denied"
```

The `name` attribute (on the left) is generally in upper case (pep8 convention for constants) while there is no constrain for the `value` attribute (on the right).

By doing:

```python
class DefaultEnumParser(Parser):
    def __init__(self, cls):
        self.cls = cls

    def parse(self, value):
        return self.cls[value]
```

instead of:

```python
class DefaultEnumParser(Parser):
    def __init__(self, cls):
        self.cls = cls

    def parse(self, value):
        return self.cls(value)
```
Pyckson forces to use the left part as the value and the right part as the human readable field. The human readable field won't be used in the code anymore and we could even abandon it with automatic values (https://docs.python.org/3/library/enum.html#using-automatic-values).

I didn't proposed a complete patch as I don't how to handle this breaking change:

- default behavior with decorator to support the old one
- keep the old behavior but propose a decorator to parse enums with values

Best regards,
Thibaut

**Comment by JGiard** [comment]
Hi,
thank you for your feedback, but I'm not sure I understand what you want.

Currently pyckson uses the `name` attribute of enumeration members to perform serialization and parsing.
Do you mean you want to be able to use the `value` attribute of enumeration members ? that seems contradictory to what you said about automatic values.

**Comment by phptib** [comment]
Hi,

Sorry, I've forgotten to respond. Yes, I would like to use the `value` attribute of enumeration members even if the `value` is automatic.

For example, we could have an embedded software inside an "human-like" robot receiving commands. Imagine that the enumeration for commands is shared between the remote control and the robot software.

```python
class Command(Enum):
    WALK = auto()
    RUN = auto()
```

Both softwares will use `Command.WALK` but the serialized command transmitted in Bluetooth will have digits given by `auto()` (0, 1, etc.) to reduce the transport time.
We could also have a program saving command on a disk for itself. Having digits in the file is also useful to reduce the file size.

I'm used to have human readable fields in the `name` attribute of enumeration members and digital/optimized value in the `value` attribute of enumeration members. The opposite is confusing for me and I would prefer this new behavior by default. But, considering you have a community using your software, it's preferable to not introduce a breaking change, so we could just add an option for this. What do you think ?

Kind regards,
Thibaut

**Comment by JGiard** [comment]
I have added the @enumvalues decorator in v1.11.0 for enum classes.
It should work with any Enum that has integer or string values.

You can also set it globally with `pyckson.set_defaults(enumvalues)`

https://pyckson.readthedocs.io/en/latest/advanced.html#enums

**Comment by phptib** [comment]
You're the best !

Thank you
