### ISSUE TITLE
Handle `datetime`

### ISSUE THREAD

**Issue by chadjaros** [antidot/Pyckson#5]
`datetime` currently throws a circular reference when attempting to be dumped. This should ideally be built into the library and support iso formats for serialization and deserialization

**Comment by JGiard** [comment]
I don't understand this one, could you provide an example ?
I have this test working fine : https://github.com/antidot/Pyckson/blob/c2562cffa7b779f2c1cf2d8ba54169c7331ed9c9/tests/serializers/test_serializer.py#L116

**Comment by chadjaros** [comment]
Ah, I think I misunderstood the intent of the library. It passes datetimes through your key mapping logic without alteration. It doesn't actually handle datetime during the the full json -> object or object -> json transform, but instead passes the buck to json.dumps and json.loads?

I expected that your logic would change a datetime into a string, and would parse a string value back into a datetime. Json.dumps/loads don't work with datetime out of the box, and if my pyckson object has a datetime field I'm at a loss for how to get an iso string value from json to marshal into a datetime without custom logic for each object.

**Comment by JGiard** [comment]
Yes, the main api methods are serialize and parse. There is a dump and load function but they are just wrappers around json.load/dump.
I don't want to alter the default behavior because it is still useful for some uses like dumping to mongo bson.
There is support for custom class serializer but it seems like what you need would be close to a custom field serializer that you attach to your datetime field.
I will investiguate what can be easily done, but it will most probably take the form of an annotation like what was done with @listtype before typing support (the outdated readme example), and maybe providing a example IsoDateSerializer.

**Comment by chadjaros** [comment]
What I'm looking for is a Jackson clone in python for json serialization. 

I came to this library from the Jackson library page, assuming that this project is what I was looking for. It's certainly closer than other available projects. However, making datetime marshalling a custom mapping rather than default behavior seems like a move in the opposite direction.

**Comment by JGiard** [comment]
To be fair I'm quite open to suggestions, this is a small project and I don't recall using any date types in my objects.
However it seems quite tricky to properly implement proper date parsing. I can use a simple isoformat() but it will only parse json dumped by pyckson. It seems like for example that Jackson uses signed timestamp to serialize dates (http://www.studytrails.com/java/json/jackson-create-json/).

Alternatively it should be easy to use a side project that does that specifically like https://github.com/nicolaiarocci/json-datetime or https://github.com/rconradharris/jsondate.

**Comment by chadjaros** [comment]
Yeah, it's certainly non-trivial. 

Jackson can be configured to either use iso-timestamps or signed integer timestamps.

I was looking at http://labix.org/python-dateutil for doing this if I needed to implement it myself.

**Comment by JGiard** [comment]
I pushed a base implementation to master.
documentation here : http://pyckson.readthedocs.io/en/latest/advanced.html#dates
The default behavior remains the same but it should be fairly easy to override it. I provided example parsers that rely on the arrow library : http://arrow.readthedocs.io/en/latest/

**Comment by chadjaros** [comment]
Cool.

This is something that would really benefit from being a global setting. That's one of the great benefits of Jackson's OO approach is that you can have multiple instances of ObjectMapper configured differently, and everything you serialize through each instance follows the expected protocol.

**Comment by chadjaros** [comment]
I see that you did add global configuration, so double awesome.
