### ISSUE TITLE
Incorrect handling of typing.Optional annotation.

### ISSUE THREAD

**Issue by chasing-nik** [antidot/Pyckson#8]
Hello,
I tried to add Optional annotation to class init method parameters:
```
class Foo:
    def __init__(self, arg1: str):
        self.arg1 = arg1

class Bar:
    def __init__(self, a_foo: Optional[Foo]):
        self.a_foo = a_foo

bar = Bar(Foo("foo"))
print(serialize(bar)
```
As a result I get default str representation of Foo class inside json:
```
{'aFoo': <__main__.Foo object at 0x00000183C982EF98>}
```

**Comment by JGiard** [comment]
There was indeed a serious bug with optional serialization, Thank you.
I will release a fix along with v1.4 (with date parsing from #5)
